### ISSUE TITLE
Error setting oauth2 credentials to a consumer with kong 0.8.2 + PostgreSQL

### ISSUE THREAD

**Issue by ammmze** [Mashape/kong#1280]
With Kong 0.8.2 running under PostgreSQL, I'm seeing an issue setting oauth2 credentials to a consumer. *Note: It seems to work find under cassandra*

Here's a docker-compose file that re-produces the issue for me:

```
version: '2'
services:
  kong-db:
    image: postgres:9.4
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    image: mashape/kong:0.8.2
    restart: always
    links:
      - 'kong-db:kong-database'
    environment:
      - DATABASE=postgres
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
    security_opt:
      - seccomp:unconfined

  kongfig:
    image: 'mashupmill/kongfig'
    links:
      - kong:kong
    environment:
      - CHECK_ATTEMPTS=60
      - DEBUG=true
      - |-
        CONFIG=---
          consumers:
            - username: someclient
              credentials:
                - name: oauth2
                  attributes:
                    name: Some Client Application
                    client_id: my-client-id
                    client_secret: secret-sauce
                    redirect_uri: http://localhost
    command: ["--path", "/config.yml", "--host", "kong:8001"]
```

I get the following when error when it tries to add the oauth2 credentials:

```
kongfig_1  | POST 500 http://kong:8001/consumers/someclient/oauth2
kongfig_1  |  { name: 'Some Client Application',
kongfig_1  |   client_id: 'my-client-id',
kongfig_1  |   client_secret: 'secret-sauce',
kongfig_1  |   redirect_uri: 'http://localhost' }
kongfig_1  | Error: Internal Server Error
kongfig_1  | {"message":"An unexpected error occurred"}
kongfig_1  |
kongfig_1  |  Error: Internal Server Error
kongfig_1  | {"message":"An unexpected error occurred"}
kongfig_1  |
kongfig_1  |     at /usr/local/lib/node_modules/kongfig/lib/core.js:173:43
kongfig_1  |     at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:89:22)
kongfig_1  |     at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:102:28
kongfig_1  |     at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
kongfig_1  |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
kongfig_1  |     at process._tickCallback (internal/process/next_tick.js:98:9)
```

And here's what we see in the kong error log /usr/local/kong/logs/error.log
Maybe this is a bug in Kong itself?

```
2016/05/31 23:50:00 [error] 109#0: *22 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: don't know how to escape value: table: 0x40c056b0
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: in function 'escape_literal'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:281: in function 'insert'
	/usr/local/share/lua/5.1/kong/dao/dao.lua:103: in function 'insert'
	/usr/local/share/lua/5.1/kong/api/crud_helpers.lua:98: in function 'post'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:57: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:56>
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:656: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 172.18.0.4, server: , request: "POST /consumers/someclient/oauth2 HTTP/1.1", host: "kong:8001"
2016/05/31 23:50:00 [error] 109#0: *22 [lua] app.lua:61: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:659: /usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: don't know how to escape value: table: 0x40c056b0
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: in function 'escape_literal'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:281: in function 'insert'
	/usr/local/share/lua/5.1/kong/dao/dao.lua:103: in function 'insert'
	/usr/local/share/lua/5.1/kong/api/crud_helpers.lua:98: in function 'post'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:57: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:56>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:659: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 172.18.0.4, server: , request: "POST /consumers/someclient/oauth2 HTTP/1.1", host: "kong:8001"
```

**Comment by thefosk** [comment]
Related to https://github.com/Mashape/kong/issues/1262 and already fixed - the next version will have the fix (coming out tomorrow).

**Comment by ammmze** [comment]
Nice ... thanks :) When I was searching for existing tickets I forgot to take off the "open" filter
